#!/bin/bash
# Small helper to remove some cruft from ~ (you may not want to remove some of these if you use firefox, or arduino, etc)
#
# Copyright (c) 2015 Dan Panzarella
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE. 



cleanhome() {
    cd ~
    rm -rf -- .arduino .binwalk .bzr.log .cache/mozilla .mozilla .cache/libimobiledevice .chirp .java ".pronsolerc~bak" .ptbt1 .rgb.txt .lesshst .python_history .gr_fftw_wisdom .esd_auth .gnuradio .gphoto .rnd .kicad .eeschema .pcbnew .cvpcb 
}


case "$1" in
    home|HOME|/home/*)
        cleanhome
        ;;
    *)
        echo "not supported" >&2
        exit 1
        ;;
esac
