#!/bin/bash
# Small convenience script for symmetrically encrypting or decrypting files with AES256
#
# Copyright (c) 2015 Dan Panzarella
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.


set -e

#check for `crypt -h`, print and exit
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    echo "Usage: $(basename "$0") FILE [OUTPUT_FILE]"
    exit
fi

command -v gpg >/dev/null 2>&1 || { echo "GPG must be installed" >&2; exit 1; }


#get input filename and make sure it can be used
readonly FILE="${1%/}" #%/ to remove any trailing slashes (esp on directories)
if [ ! -e "$FILE" -o ! -f "$FILE" -a ! -d "$FILE"  -o ! -r "$FILE" -o ! -s "$FILE" ]; then
    echo "Cannot use "$FILE", might not be readable, or might be empty" >&2
    exit 1
fi


#get output name, if given
if [ -z "$2" ]; then
    OUTPUT="$2"
fi


#get password for en- or de-crypting

printf "Enter password: "
#alternative (bash-specific): read -s
stty_save=`stty -g` #save terminal settings
stty -echo          #turn off echoing
read passwd
stty $stty_save     #restore settings

printf '\n'


#to get command-line prompt in gpgv2 and not ncurses-based:
# > gpg-agent.conf
# pinentry-program /usr/bin/pinentry-curses
# allow-loopback-pinentry
#
#and then use `gpg --pinentry-mode loopback ...` and you will get a prompt
#here, we prompt earlier and pass it as an option using --passphrase, but that is not required.

if file -b "$FILE" | grep "GPG.*encrypted" >/dev/null 2>&1; then
    #input file is already encrypted, we are decrypting
    echo "decrypting.."
    gpg --pinentry-mode loopback --passphrase "$passwd" -d -o "${OUTPUT:-${FILE%.gpg}}" "${FILE}"

    #if bzipped, we're not done. was probably a dir
    if file -b "${OUTPUT:-${FILE%.gpg}}" | grep "^bzip2" >/dev/null 2>&1; then
        tar -xjf "${OUTPUT:-${FILE%.gpg}}"
    fi


    rm -rf "$FILE"

else
    #input file is not encrypted, we will encrypt
    echo "encrypting.."

    #directories can't be gpg'd directly. tar first
    if [ -d "$FILE" ];then
        tar -cjf "${FILE}.tar.bz" "$FILE"
        gpg --pinentry-mode loopback --passphrase "$passwd" -c --cipher-algo aes256 -z 0 -o "${OUTPUT:-${FILE}.gpg}" "${FILE}.tar.bz"
        rm -rf "${FILE}.tar.bz"
    else
        gpg --pinentry-mode loopback --passphrase "$passwd" -c --cipher-algo aes256  --compress-algo bzip2 -z 9 -o "${OUTPUT:-${FILE}.gpg}" "${FILE}"
    fi
    rm -rf "$FILE"
fi


