#!/bin/sh
xrandr \
    --output DVI-I-1 \
        --mode 1920x1080 \
        --pos 3840x0 \
        --rotate normal \
    --output DVI-D-0 \
        --mode 1920x1080 \
        --pos 5760x0 \
        --rotate normal

nitrogen --restore >/dev/null 2>&1

( exec -a "second-bar" ~/dev/statbar/statbar 1920x22+3840+0 ) & disown

~/.config/bspwm/bspwmrc
