#!/bin/sh
xrandr \
    --output DVI-I-1 \
        --mode 1920x1080 \
        --pos 3840x0 \
        --rotate normal \
    --output DVI-D-0 \
        --mode 1920x1080 \
        --pos 5760x0 \
        --rotate normal

<<COMMENT
    --output DP-1 \
        --mode 1920x1080 \
        --pos 0x0 \
        --rotate normal \
    --output HDMI-0 \
        --mode 1920x1080 \
        --pos 1920x0 \
        --rotate normal \
    --output DVI-I-0 \
        --off \
    --output DP-0 \
        --off
COMMENT


bspc desktop ^3:^1 -n a
bspc monitor ^3 -a b c

bspc desktop ^4:^1 -n A
bspc monitor ^4 -a B C

nitrogen --restore >/dev/null 2>&1

bspc config -m ^3 top_padding 20

~/dev/statbar/statbar 1920x22+3840+0 &

#~/.config/bspwm/bspwmrc
