#!/bin/bash


ARG="$1"

if [ -z "$ARG" ]; then
    ARG=$(xwininfo | grep -Po "0x[\da-f]+" -m1)
fi

if [[ $ARG == 0x* ]]; then
    ARG="$(xprop -id "$ARG" '=$0' _NET_WM_PID | cut -d= -f2)"
fi


echo "/dev/$(ps h --ppid $ARG -o tty)"

set +x
