#!/bin/bash
# Small convenience script for backing up iOS devices
#
# Copyright (c) 2014 Dan Panzarella
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE. 


BACKUP_PATH=/run/media/dan/extra/ios
IBACKUP=$( command -v idevicebackup2 )
if [ $? -ne 0 ]; then
    echo >&2 "idevicebackup2 is required, but was not found. Please install libimobiledevice"
    exit 1
fi

# If you keep getting device not found, try manually starting usbmuxd with the phone already plugged in, with:
# sudo usbmuxd -f -v
# in another terminal, and trying this again with that running.


$IBACKUP backup --full $BACKUP_PATH

#restore
#$IBACKUP --source <UDID> restore --system --settings --reboot -i $BACKUP_PATH
