#!/bin/bash
# Lock screen options wrapper
#
# Copyright (c) 2015 Dan Panzarella
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE. 


readonly help="Usage:
`basename $0` [OPTS]
    -h  help
    -b  show a blurred screen
    -p  show a pixelated screen
    -w  show pixelated windows
    -a  TEXT  annotate the screen with TEXT
    -k  keep the status bar on top
"
readonly FNAME="/tmp/lockshot.png"


while getopts :hpwbka: opt; do
    case "$opt" in
        h)
            echo "$help"
            exit 0
            ;;
        \?)
            echo "Invalid arg: -$OPTARG" >&2
            echo "$help"
            exit 1
            ;;
        :)
            echo "-$OPTARG requires an argument" >&2
            echo "$help"
            exit 1
            ;;
        k) status_bar=true;;
        b)
            blur=true
            pixel=false
            pix_win=false
            ;;
        p)
            pixel=true
            blur=false
            pix_win=false
            ;;
        w)
            pixel=false
            blur=false
            pix_win=true
            ;;
        a)
            text="$OPTARG"
            annotate=true
            ;;
    esac
done

scrot "$FNAME"

if [ "$blur" = true ]; then
    convert "$FNAME" -blur 0x20 "$FNAME"
elif [ "$pixel" = true ]; then
    convert "$FNAME" -scale 10% -scale 1000% "$FNAME"
elif [ "$pix_win" = true ]; then
    pixelate_windows "$FNAME"
fi

if [ "$annotate" = true ]; then
    convert "$FNAME" -gravity northwest -font Courier-bold -pointsize 15 -annotate +30+35 "$text" "$FNAME"
fi

if [ "$status_bar" = true ];then
    killall "bar-init"
fi

i3lock -b -u -e -i "$FNAME"
#maybe -p default to show things aren't frozen?

rm -rf "$FNAME"


if [ "$status_bar" = true ]; then
    ~/.config/lemonbar/bar-init &
fi
