#!/bin/bash
# Script to setup a few necessities for LXC dev on an external drive
# and set up bridged networking
#
# Copyright (c) 2014 Dan Panzarella
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE. 


#need dev option for some of the linux system files to work
if mountpoint /run/media/dan/overflow >/dev/null 2>&1; then
    sudo mount -o remount,dev,suid /run/media/dan/overflow
else
    echo "Please mount overflow drive"
    exit 1
    #sudo mount -o rw,suid,relatime,data=ordered -t ext4 /dev/sdf3 /run/media/dan/overflow
fi

#####
# Networking setup
####

# OLD METHOD USING WIFI
#sudo brctl addbr br0
#sudo ifconfig br0 10.0.2.1/24
#sudo ifconfig

#sudo iptables -t nat -A POSTROUTING -s 10.0.2.2/24 -j MASQUERADE
#sudo sysctl net.ipv4.ip_forward=1


# NEW-NEW method on wired, using networkmanager instead of netcl
CON_NAME="3d49251c-45e9-4aed-beb7-2b036f121ec7"

if ! nmcli con show $CON_NAME | grep activated >/dev/null 2>&1; then
    nmcli con up $CON_NAME
fi

# NEW METHOD ON WIRED:
#sudo netctl start lxcbridge
# /etc/netctl/lxcbridge:
#Description="LXC bridge"
#Interface=br0
#Connection=bridge
#BindsToInterfaces=('enp14s0')
#IP=dhcp
#SkipForwardingDelay=yes





#things to do on setting up new machine:
#   Config file:   
#   lxc.network.link = br0
#   lxc.network.name = enp14s0
#   lxc.network.mtu = 1500
#   lxc.network.ipv4 = 192.168.1.99/24
#   lxc.network.ipv4.gateway = 192.168.1.1

#   In machine:
#   apt-get update
#   apt-get install apt-utils
#   apt-get upgrade
#   apt-get install sudo vim inetutils-ping dnsutils curl bash-completion
#   useradd -m -G sudo -s /bin/bash dan
#   passwd dan


# debian lamp stack packages: mysql-server apache2 php5 php5-mysql libapache2-mod-php5
# apache: don't forget to enable mods (rewrite) and a2ensite, etc
