#!/bin/bash

if [ $# -lt 1 ]; then
  echo "required argument: process name to grep for"
  exit 1
fi

ps -eo pmem,comm,pid,maj_flt,min_flt,rss,vsz --sort -rss | numfmt --header --to=iec --field 4-5 | numfmt --header --from-unit=1024 --to=iec --field 6-7 | column -t | egrep "[P]ID|$1"
