#!/bin/bash


main(){
    local wid=$(xdotool search --limit 1 --name dropterm)

    if [ -n "$wid" ]; then
        if xwininfo -id $wid | grep "Map State: IsUnMapped" >/dev/null 2>&1; then
            xdotool windowmap --sync $wid
        else
            xdotool windowunmap $wid
        fi
    else
        terminator -r quake -l quake 
    fi

}

main $@
