#!/bin/bash


main(){
    local wid=$(xdotool search --limit 1 --name dropterm)

    if [ -n "$wid" ]; then
        if xwininfo -id $wid | grep "Map State: IsUnMapped" >/dev/null 2>&1; then
            xdotool windowmap --sync $wid
            #xdo move -x 0 -y 0 $wid
            #xdo resize -w 1920 -h 300 $wid
            #bspc node $wid -g hidden -m pointed -f
        else
            #bspc node $wid -g hidden
            xdotool windowunmap $wid
        fi
    else
        terminator -r quake -l quake 
    fi

}

main $@
