#!/bin/bash

ffmpeg -f x11grab -s 1920x1080 -r 24 -i $DISPLAY -f alsa -i default -c:v libx264 -b:a 200k -y "cast-$(date +"%F-%I-%M-%s").mkv"
#ffmpeg -f x11grab -s 1920x1080 -r 24 -i $DISPLAY -f alsa -i default -c:v libx265 -preset medium -x265-params crf=28 -strict experimental -b:a 200k "cast-265.mkv"
