#!/bin/bash
# My window manager rules for BSPWM
#
# Copyright (c) 2014 Dan Panzarella
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE. 


readonly ID="$1"
readarray -t PROPS < <(xwinfo -its $1)

INST=${PROPS[0]}
TYPE=${PROPS[1]}
STATE=(${PROPS[2]})

RULE=()

#defaults
case "$TYPE" in
	dock|desktop|notification)	RULE+=("manage=off") ;;
	toolbar|utility)			RULE+=("focus=off") ;;
	desktop)					RULE+=("layer=below") ;;
esac

for s in $STATE; do
	case $s in
		sticky)					RULE+=("sticky=on") ;;
		fullscreen)				RULE+=("state=fullscreen") ;;
	esac
done


#custom rules
case "$INST" in
	Google-chrome*|google-chrome*|nitrogen|gimp*|ruler|gbdfed|zoom)
		RULE+=("state=floating") ;;
	BSPWM_FRAME|bspwm_frame)
		RULE+=("frame=on") ;;
    xmessage|tint2)
        RULE+=("manage=off") ;;
    blue)
        RULE+=("state=floating") ;;
    Blender)
        RULE+=("locked=on") ;; #prevent accidental closing
esac

# Debug:
#echo "got ID: <$1> class <$2> instance <$3> and read -its as <$INST><$TYPE><$STATE> and then gave as output: ${RULE[*]}" >> ~/tmp/bspwm-tiling

echo "${RULE[*]}"
