#!/bin/bash
# My window manager rules for BSPWM
#
# Copyright (c) 2014 Dan Panzarella
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE. 

set -e

cleanup() {
  set +e
  status=$?
  echo "$(date -Is): <> tiling_rules failure?" >> /var/log/tiling_rules.log
  trap - INT TERM
  exit "$status"
}
trap cleanup INT TERM

readonly ID="$1"
readarray -t PROPS < <(xwinfo -cints "$ID")


INST=${PROPS[1]}
NAME=${PROPS[2]}
TYPE=${PROPS[3]}
STATE=(${PROP[4]})
ROLE=$( xprop -id "$ID" '=$0' WM_WINDOW_ROLE | grep = | cut -d= -f2 | tr -d '"' )

RULE=()

#defaults
case "$TYPE" in
	dock|desktop|notification)	RULE+=("manage=off") ;;
	toolbar|utility)			RULE+=("focus=off") ;;
  dialog)           RULE+=("layer=above") ;;
	#desktop)					RULE+=("layer=below") ;;
esac

for s in $STATE; do
	case $s in
		sticky)					RULE+=("sticky=on") ;;
		fullscreen)				RULE+=("state=fullscreen") ;;
        above)                  RULE+=("layer=above") ;;
	esac
done


case "$NAME" in
    'Poly Bridge'|'Unturned 3'|RaceTheSun|Broforce|'TowerFall Ascension'|'ShellShock Live')
        RULE+=("state=fullscreen") ;;
    ImageMagick*|QuickNotes)
      RULE+=("state=floating");; # python PIL.Image.show() uses imagemagick for preview
esac

#custom rules
case "$INST" in
    stalonetray|gcr-prompter|pinentry*|gimp*|ruler|zoom)
      RULE+=("state=floating")
        RULE+=("layer=above") ;;
	Google-chrome*|google-chrome*|nitrogen|gbdfed|zoom|simulator.exe|gtk.py|pdfpc|libovg|slack-notif)
		RULE+=("state=floating") ;;
	BSPWM_FRAME|bspwm_frame)
		RULE+=("frame=on") ;;
    xmessage|tint2)
        RULE+=("manage=off") ;;
    Blender)
        RULE+=("locked=on") ;; #prevent accidental closing
esac

case "$ROLE" in
    quake) #terminal drop-down aka quake-mode
        RULE+=("state=floating")
        RULE+=("layer=above")
        RULE+=("locked=on")
        RULE+=("focus=on")
        RULE+=("rectangle=3840x600+0+0")
        ;;
esac




# Debug:
#echo -e "got ID: <$1> and read -cints as\n\tclass: <$2>\n\tinst: <$INST>\n\tname: <$NAME>\n\ttype: <$TYPE>\n\tstate: <$STATE>\n\trole: <$ROLE>\n\tand then gave as output: ${RULE[*]}" >> /tmp/rules.log


echo "${RULE[*]}"
